# Generated by Django 6.0.7 on 2026-08-18 23:13

import datetime
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('check_type', models.CharField(default='present', max_length=20)),
                ('match_pattern', models.CharField(max_length=500)),
                ('expected_entries', models.JSONField(blank=True, default=list)),
                ('add_template', models.CharField(blank=True, max_length=500)),
                ('remove_template', models.CharField(blank=True, max_length=500)),
                ('auto_remediable', models.BooleanField(default=True)),
                ('allow_enforce', models.BooleanField(default=False)),
                ('remediation_notes', models.TextField(blank=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('device_tags', models.ManyToManyField(blank=True, related_name='scoped_config_standards', to='extras.tag')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('platforms', models.ManyToManyField(blank=True, related_name='config_standards', to='dcim.platform')),
                ('roles', models.ManyToManyField(blank=True, related_name='config_standards', to='dcim.devicerole')),
                ('sites', models.ManyToManyField(blank=True, related_name='config_standards', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'config standard',
                'verbose_name_plural': 'config standards',
                'ordering': ('name', '-valid_from'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('result', models.CharField(default='unknown', max_length=20)),
                ('observed', models.TextField(blank=True)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('pre_change_config', models.TextField(blank=True)),
                ('pre_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_remediated', models.DateTimeField(blank=True, null=True)),
                ('remediation_log', models.TextField(blank=True)),
                ('exempt', models.BooleanField(default=False)),
                ('exempt_reason', models.TextField(blank=True)),
                ('exempt_approved_by', models.CharField(blank=True, max_length=100)),
                ('exempt_approved_on', models.DateField(blank=True, null=True)),
                ('exempt_review_by', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_compliance', to='dcim.device')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='netbox_compliance.configstandard')),
            ],
            options={
                'verbose_name': 'config compliance',
                'verbose_name_plural': 'config compliance',
                'ordering': ('device', 'standard'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='configstandard',
            index=models.Index(fields=['name'], name='netbox_comp_name_7e9e47_idx'),
        ),
        migrations.AddIndex(
            model_name='configstandard',
            index=models.Index(fields=['valid_from', 'valid_to'], name='netbox_comp_valid_f_586402_idx'),
        ),
        migrations.AddIndex(
            model_name='configstandard',
            index=models.Index(fields=['check_type'], name='netbox_comp_check_t_fea874_idx'),
        ),
        migrations.AddConstraint(
            model_name='configstandard',
            constraint=models.UniqueConstraint(models.F('name'), models.F('valid_from'), name='netbox_compliance_configstandard_unique_name_from', violation_error_message='A standard with that name already starts on that date.'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['result'], name='netbox_comp_result_df42f5_idx'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['exempt'], name='netbox_comp_exempt_7a0fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['last_checked'], name='netbox_comp_last_ch_642434_idx'),
        ),
        migrations.AddConstraint(
            model_name='configcompliance',
            constraint=models.UniqueConstraint(models.F('device'), models.F('standard'), name='netbox_compliance_configcompliance_unique_device_standard', violation_error_message='That device already has a result for this standard.'),
        ),
    ]
