# Generated by Django 6.0.7 on 2026-10-07 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def baseline_revisions(apps, schema_editor):
    Standard = apps.get_model('netbox_compliance', 'ConfigStandard')
    Revision = apps.get_model('netbox_compliance', 'ConfigStandardRevision')
    fields = ('name', 'check_type', 'match_pattern', 'expected_entries', 'add_template',
              'remove_template', 'auto_remediable', 'allow_enforce', 'remediation_notes',
              'description', 'comments')
    for standard in Standard.objects.using(schema_editor.connection.alias).all():
        definition = {name: getattr(standard, name) for name in fields}
        for name in ('platforms', 'roles', 'sites', 'device_tags'):
            definition[name] = sorted(getattr(standard, name).values_list('pk', flat=True))
        definition.update(valid_from=standard.valid_from.isoformat(),
                          valid_to=standard.valid_to.isoformat() if standard.valid_to else None,
                          settings={})
        Revision.objects.using(schema_editor.connection.alias).create(
            standard_id=standard.pk, number=1, definition=definition)
        Standard.objects.using(schema_editor.connection.alias).filter(pk=standard.pk).update(revision=1)


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configstandard',
            name='definition_yaml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configstandard',
            name='revision',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='configstandard',
            name='match_pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ConfigStandardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('definition_yaml', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='netbox_compliance.configstandard')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='configcompliance',
            name='standard_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='netbox_compliance.configstandardrevision'),
        ),
        migrations.AddConstraint(
            model_name='configstandardrevision',
            constraint=models.UniqueConstraint(fields=('standard', 'number'), name='config_standard_revision_unique'),
        ),
        migrations.RunPython(baseline_revisions, migrations.RunPython.noop),
    ]
