# Generated by Django 6.0.7 on 2026-08-01 01:44

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0237_module_remove_local_context_data'),
        ('extras', '0140_imageattachment_image_size'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('end_of_sale', models.DateField(blank=True, null=True)),
                ('end_of_sw_maintenance', models.DateField(blank=True, null=True)),
                ('end_of_security_support', models.DateField(blank=True, null=True)),
                ('end_of_routine_failure_analysis', models.DateField(blank=True, null=True)),
                ('end_of_service_attach', models.DateField(blank=True, null=True)),
                ('end_of_service_contract_renewal', models.DateField(blank=True, null=True)),
                ('end_of_support', models.DateField(blank=True, null=True)),
                ('bulletin_number', models.CharField(blank=True, max_length=50)),
                ('bulletin_url', models.URLField(blank=True, max_length=500)),
                ('replacement_notes', models.TextField(blank=True)),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cost_updated', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('assigned_object_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ('devicetype', 'moduletype'))), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('replacement_device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_lifecycles', to='dcim.devicetype')),
                ('replacement_module_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_lifecycles', to='dcim.moduletype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'model lifecycle',
                'verbose_name_plural': 'model lifecycles',
                'ordering': ('end_of_support', 'pk'),
                'indexes': [models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='netbox_refr_assigne_d93376_idx'), models.Index(fields=['end_of_support'], name='netbox_refr_end_of__de9f88_idx')],
                'constraints': [models.UniqueConstraint(models.F('assigned_object_type'), models.F('assigned_object_id'), name='netbox_refresh_modellifecycle_unique_object', violation_error_message='This hardware model already has a lifecycle record.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
