# Generated by Django 6.0.7 on 2026-08-09 06:16

import datetime
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_refresh', '0001_initial'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('version', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_file', models.FileField(blank=True, upload_to='netbox-refresh/images/')),
                ('image_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum_type', models.CharField(blank=True, max_length=10)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_versions', to='dcim.platform')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'software version',
                'verbose_name_plural': 'software versions',
                'ordering': ('platform', 'version'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoftwareStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('assigned_object_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ('devicetype', 'platform'))), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('approved_versions', models.ManyToManyField(related_name='approved_by_standards', to='netbox_refresh.softwareversion')),
                ('preferred_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_standards', to='netbox_refresh.softwareversion')),
            ],
            options={
                'verbose_name': 'software standard',
                'verbose_name_plural': 'software standards',
                'ordering': ('-valid_from', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('raw_version', models.CharField(blank=True, max_length=200)),
                ('raw_report', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('exempt', models.BooleanField(default=False)),
                ('exempt_reason', models.TextField(blank=True)),
                ('exempt_approved_by', models.CharField(blank=True, max_length=100)),
                ('exempt_approved_on', models.DateField(blank=True, null=True)),
                ('exempt_review_by', models.DateField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='dcim.device')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('software_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='netbox_refresh.softwareversion')),
            ],
            options={
                'verbose_name': 'device software',
                'verbose_name_plural': 'device software',
                'ordering': ('device',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='softwareversion',
            index=models.Index(fields=['version'], name='netbox_refr_version_4454ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(models.F('platform'), models.F('version'), name='netbox_refresh_softwareversion_unique_platform_version', violation_error_message='That version already exists for this platform.'),
        ),
        migrations.AddIndex(
            model_name='softwarestandard',
            index=models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='netbox_refr_assigne_cca28d_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarestandard',
            index=models.Index(fields=['valid_from', 'valid_to'], name='netbox_refr_valid_f_3fd07a_idx'),
        ),
        migrations.AddConstraint(
            model_name='softwarestandard',
            constraint=models.UniqueConstraint(models.F('assigned_object_type'), models.F('assigned_object_id'), models.F('valid_from'), name='netbox_refresh_softwarestandard_unique_scope_from', violation_error_message='This device type or platform already has a standard starting on that date.'),
        ),
        migrations.AddIndex(
            model_name='devicesoftware',
            index=models.Index(fields=['software_version'], name='netbox_refr_softwar_ec0c28_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesoftware',
            index=models.Index(fields=['exempt'], name='netbox_refr_exempt_9a5a8a_idx'),
        ),
    ]
