# Generated by Django 6.0.7 on 2026-08-09 06:49
#
# Images are published to the internal HTTP file server, not uploaded into
# NetBox, so the FileField had no job. Dropping it removes a 300MB-1GB upload
# path through Apache and gunicorn that would only ever have timed out, and
# removes the possibility of two copies of one image disagreeing. The link
# (image_url, or image_filename plus the image_base_url setting) is the record.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_refresh', '0002_softwareversion_softwarestandard_devicesoftware_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareversion',
            name='image_file',
        ),
    ]
