# Generated by Django 6.0.7 on 2026-08-20, then edited: the data copy between
# the field additions and removals is hand-written, because the autodetector
# cannot know that the old generic FK rows become M2M memberships.

from django.db import migrations, models


def scope_to_m2m(apps, schema_editor):
    """Every standard's single generic-FK scope becomes one M2M membership."""
    SoftwareStandard = apps.get_model('netbox_refresh', 'SoftwareStandard')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_types = {ct.pk: ct.model for ct in ContentType.objects.all()}
    for standard in SoftwareStandard.objects.exclude(assigned_object_type=None):
        model = content_types.get(standard.assigned_object_type_id)
        if model == 'devicetype':
            standard.device_types.add(standard.assigned_object_id)
        elif model == 'platform':
            standard.platforms.add(standard.assigned_object_id)


def m2m_to_scope(apps, schema_editor):
    """Best-effort reverse: only possible while every standard has one scope.

    A standard covering several device types cannot be expressed in the old
    schema, so rather than silently dropping scopes, refuse to reverse.
    """
    SoftwareStandard = apps.get_model('netbox_refresh', 'SoftwareStandard')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for standard in SoftwareStandard.objects.all():
        device_types = list(standard.device_types.all())
        platforms = list(standard.platforms.all())
        if len(device_types) + len(platforms) > 1:
            raise RuntimeError(
                'Standard %s covers %d scopes; the old schema holds exactly '
                'one. Split it up before reversing this migration.'
                % (standard.pk, len(device_types) + len(platforms))
            )
        if device_types:
            ct = ContentType.objects.get(app_label='dcim', model='devicetype')
            standard.assigned_object_type_id = ct.pk
            standard.assigned_object_id = device_types[0].pk
            standard.save()
        elif platforms:
            ct = ContentType.objects.get(app_label='dcim', model='platform')
            standard.assigned_object_type_id = ct.pk
            standard.assigned_object_id = platforms[0].pk
            standard.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('netbox_refresh', '0003_remove_softwareversion_image_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='softwarestandard',
            name='netbox_refresh_softwarestandard_unique_scope_from',
        ),
        migrations.RemoveIndex(
            model_name='softwarestandard',
            name='netbox_refr_assigne_cca28d_idx',
        ),
        migrations.AddField(
            model_name='softwarestandard',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='software_standards', to='dcim.devicetype'),
        ),
        migrations.AddField(
            model_name='softwarestandard',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='software_standards', to='dcim.platform'),
        ),
        # The copy must sit between the adds and the removes: it reads the old
        # columns and writes the new tables, so both have to exist.
        migrations.RunPython(scope_to_m2m, m2m_to_scope),
        migrations.RemoveField(
            model_name='softwarestandard',
            name='assigned_object_id',
        ),
        migrations.RemoveField(
            model_name='softwarestandard',
            name='assigned_object_type',
        ),
    ]
