# Generated by Django 6.0.7 on 2026-08-20 20:26

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_refresh', '0004_softwarestandard_multi_scope'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cost_updated', models.DateField(blank=True, null=True)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_prices', to='netbox_refresh.modellifecycle')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_prices', to='dcim.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_prices', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'replacement price',
                'verbose_name_plural': 'replacement prices',
                'ordering': ('lifecycle', 'region', 'site', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('region__isnull', False), ('site__isnull', True)), models.Q(('region__isnull', True), ('site__isnull', False)), _connector='OR'), name='netbox_refresh_replacementprice_exactly_one_scope', violation_error_message='A price is scoped to a region or a site — exactly one.'), models.UniqueConstraint(models.F('lifecycle'), models.F('region'), condition=models.Q(('region__isnull', False)), name='netbox_refresh_replacementprice_unique_region', violation_error_message='This model already has a price for that region.'), models.UniqueConstraint(models.F('lifecycle'), models.F('site'), condition=models.Q(('site__isnull', False)), name='netbox_refresh_replacementprice_unique_site', violation_error_message='This model already has a price for that site.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
