# Generated by Django 6.0.7 on 2026-08-20, then edited: prices re-key from the
# outgoing model's lifecycle to the hardware model being PURCHASED, and the
# data step between the field additions and removals is hand-written. The
# constraints move after it so existing rows are re-keyed before any rule that
# would reject them exists. Per Jason: "It's less what the replacement cost.
# It's more what the new one cost."

import django.db.models.deletion
from django.db import migrations, models


def lifecycle_to_model(apps, schema_editor):
    """Re-key each price onto its lifecycle's replacement model.

    A price on a lifecycle with no replacement recorded cannot be expressed
    in the new schema (there is no "new one" to attach it to) and is deleted.
    0005 and 0006 ship in the same release, so in practice this migrates
    nothing but development data.
    """
    ReplacementPrice = apps.get_model('netbox_refresh', 'ReplacementPrice')
    for price in ReplacementPrice.objects.select_related('lifecycle'):
        lifecycle = price.lifecycle
        if lifecycle.replacement_device_type_id:
            price.device_type_id = lifecycle.replacement_device_type_id
            price.save()
        elif lifecycle.replacement_module_type_id:
            price.module_type_id = lifecycle.replacement_module_type_id
            price.save()
        else:
            price.delete()


def model_to_lifecycle(apps, schema_editor):
    """Reverse: attach each price back to a lifecycle replaced by its model.

    Several lifecycles can share one replacement; the old schema wants one
    lifecycle per price, so the first is taken and the rest re-learn the
    price through it. Prices whose model no lifecycle names are deleted.
    """
    ReplacementPrice = apps.get_model('netbox_refresh', 'ReplacementPrice')
    ModelLifecycle = apps.get_model('netbox_refresh', 'ModelLifecycle')
    for price in ReplacementPrice.objects.all():
        if price.device_type_id:
            lifecycle = ModelLifecycle.objects.filter(
                replacement_device_type_id=price.device_type_id).first()
        else:
            lifecycle = ModelLifecycle.objects.filter(
                replacement_module_type_id=price.module_type_id).first()
        if lifecycle is None:
            price.delete()
        else:
            price.lifecycle_id = lifecycle.pk
            price.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('netbox_refresh', '0005_replacementprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replacementprice',
            options={'ordering': ('device_type', 'module_type', 'region', 'site', 'pk')},
        ),
        migrations.AddField(
            model_name='replacementprice',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_prices', to='dcim.devicetype'),
        ),
        migrations.AddField(
            model_name='replacementprice',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_prices', to='dcim.moduletype'),
        ),
        migrations.RunPython(lifecycle_to_model, model_to_lifecycle),
        migrations.RemoveConstraint(
            model_name='replacementprice',
            name='netbox_refresh_replacementprice_unique_region',
        ),
        migrations.RemoveConstraint(
            model_name='replacementprice',
            name='netbox_refresh_replacementprice_unique_site',
        ),
        migrations.RemoveField(
            model_name='replacementprice',
            name='lifecycle',
        ),
        migrations.AddConstraint(
            model_name='replacementprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device_type__isnull', False), ('module_type__isnull', True)), models.Q(('device_type__isnull', True), ('module_type__isnull', False)), _connector='OR'), name='netbox_refresh_replacementprice_exactly_one_model', violation_error_message='A price is for a device type or a module type — exactly one.'),
        ),
        migrations.AddConstraint(
            model_name='replacementprice',
            constraint=models.UniqueConstraint(models.F('device_type'), models.F('region'), condition=models.Q(('device_type__isnull', False), ('region__isnull', False)), name='netbox_refresh_replacementprice_unique_dt_region', violation_error_message='This model already has a price for that region.'),
        ),
        migrations.AddConstraint(
            model_name='replacementprice',
            constraint=models.UniqueConstraint(models.F('device_type'), models.F('site'), condition=models.Q(('device_type__isnull', False), ('site__isnull', False)), name='netbox_refresh_replacementprice_unique_dt_site', violation_error_message='This model already has a price for that site.'),
        ),
        migrations.AddConstraint(
            model_name='replacementprice',
            constraint=models.UniqueConstraint(models.F('module_type'), models.F('region'), condition=models.Q(('module_type__isnull', False), ('region__isnull', False)), name='netbox_refresh_replacementprice_unique_mt_region', violation_error_message='This model already has a price for that region.'),
        ),
        migrations.AddConstraint(
            model_name='replacementprice',
            constraint=models.UniqueConstraint(models.F('module_type'), models.F('site'), condition=models.Q(('module_type__isnull', False), ('site__isnull', False)), name='netbox_refresh_replacementprice_unique_mt_site', violation_error_message='This model already has a price for that site.'),
        ),
    ]
