# Generated by Django 6.0.7 on 2026-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_refresh', '0006_replacementprice_keyed_to_purchased_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellifecycle',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
