# Generated by Django 6.0.7 on 2026-08-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0093_alter_prefix__region_alter_prefix__site_group'),
        ('netbox_discovery', '0001_initial'),
        ('tenancy', '0024_default_ordering_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverypoller',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='used_default_region',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ipam.vrf'),
        ),
    ]
