# Generated by Django 6.0.7 on 2026-08-09 16:49

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_discovery', '0002_discoverypoller_tenant_onboardingrequest_tenant_and_more'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('kind', models.CharField(default='chassis', max_length=20)),
                ('module_bay', models.CharField(blank=True, max_length=100)),
                ('old_serial', models.CharField(max_length=100)),
                ('new_serial', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('detected_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_replacements', to='dcim.device')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('poller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_discovery.discoverypoller')),
                ('replaced_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'hardware replacement',
                'verbose_name_plural': 'hardware replacements',
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['old_serial'], name='netbox_disc_old_ser_81bb1c_idx'), models.Index(fields=['new_serial'], name='netbox_disc_new_ser_a763df_idx'), models.Index(fields=['-detected_at'], name='netbox_disc_detecte_8e00ed_idx')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
