# Generated by Django 6.0.7 on 2026-08-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_discovery', '0003_hardwarereplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='manually_entered',
            field=models.BooleanField(default=False),
        ),
    ]
