# Generated by Django 6.0.7 on 2026-08-09 20:23

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_discovery', '0004_onboardingrequest_manually_entered'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('kind', models.CharField(default='duplicate-serial', max_length=30)),
                ('status', models.CharField(default='open', max_length=20)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('reported_name', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery_issues', to='dcim.device')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('poller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_discovery.discoverypoller')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'discovery issue',
                'verbose_name_plural': 'discovery issues',
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['status'], name='netbox_disc_status_545c4f_idx'), models.Index(fields=['serial'], name='netbox_disc_serial_172fe7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('address', 'serial', 'kind'), name='netbox_discovery_unique_open_issue')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
