# Generated by Django 6.0.7 on 2026-10-07 21:44

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_discovery', '0013_prestagepolicy'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradejob',
            name='profile_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(max_length=16)),
                ('plan', models.JSONField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('kind', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profiles', to='dcim.devicetype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('remediation_profile', models.ForeignKey(blank=True, limit_choices_to={'kind': 'remediate'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remediation_models', to='netbox_discovery.jobprofile')),
                ('upgrade_profile', models.ForeignKey(blank=True, limit_choices_to={'kind': 'upgrade'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_models', to='netbox_discovery.jobprofile')),
            ],
            options={
                'verbose_name': 'model profile assignment',
                'ordering': ('device_type__manufacturer__name', 'device_type__model'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
