# Generated by Django 6.0.7 on 2026-10-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_discovery', '0015_image_staging_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradejob',
            name='standards_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
