# Generated by Django 6.0.7 on 2026-10-08 04:28

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_discovery', '0017_configuration_audit'),
        ('users', '0016_default_ordering_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField()),
                ('dispatched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(max_length=10)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('job_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-scheduled_for', '-pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='upgradejob',
            name='audit_run',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='netbox_discovery.auditrun'),
        ),
        migrations.CreateModel(
            name='AuditSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='daily', max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('local_time', models.TimeField(default=datetime.time(2, 0))),
                ('time_zone', models.CharField(default='UTC', max_length=64)),
                ('window_hours', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('filters', models.JSONField(default=dict)),
                ('profile_source', models.CharField(default='custom', max_length=10)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('run_as', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('saved_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_schedules', to='netbox_discovery.jobprofile')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='netbox_discovery.auditschedule'),
        ),
        migrations.AddConstraint(
            model_name='auditrun',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='unique_audit_occurrence'),
        ),
    ]
