# Generated by Django 6.0.7 on 2026-10-08 05:43

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_discovery', '0018_auditrun_upgradejob_audit_run_auditschedule_and_more'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standards_profile', to='dcim.platform')),
                ('remediation_profile', models.ForeignKey(limit_choices_to={'kind': 'remediate'}, on_delete=django.db.models.deletion.PROTECT, related_name='remediation_platforms', to='netbox_discovery.jobprofile')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'platform profile assignment',
                'ordering': ('platform__name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
