# Generated by Django 6.0.7 on 2026-10-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_discovery', '0019_platform_standards_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradejob',
            options={'ordering': ('-scheduled_at', '-pk'), 'permissions': [('run_upgradejob', 'Execute scheduled device jobs'), ('apply_upgradejob', 'Schedule image staging and upgrades')]},
        ),
    ]
