# Generated by Django 6.0.7 on 2026-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_discovery', '0020_device_job_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditschedule',
            name='remediate',
            field=models.BooleanField(default=False),
        ),
    ]
