"""Run net-snmp's CLI tools and parse what they print.

Why the CLI and not a Python SNMP library: pysnmp's API has been rewritten
more than once and the package name has moved around, so a poller box pinned a
year ago and one built today do not agree on how to open a session. net-snmp's
command-line tools have parsed the same arguments and printed the same output
for two decades and are already on every network-adjacent Linux box.

Credentials never appear on the command line. Anything passed as argv is world
readable through `ps` for as long as the process lives, and an SNMPv3 auth or
privacy passphrase is a real credential. Instead each credential set is written
to a private `snmp.conf` in a 0700 temp directory and net-snmp is pointed at it
with SNMPCONFPATH. The file is removed when the scan finishes.

Output format: `-On -Oe` rather than the `-Oq` that looks tidier. `-Oq` drops
the type tag, and the type tag is what distinguishes `Hex-STRING: 00 11 22`
(a MAC) from `STRING: 00 11 22` (a label that happens to look like one), and
what tells us an OID column holds a RowPointer we need to decode. Losing it
would mean guessing, which is the habit this whole tool exists to break.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field

# net-snmp exit statuses and messages are not stable enough to branch on, so we
# classify by matching the text it prints. These are the messages net-snmp 5.x
# emits; each is anchored enough not to collide with a device's own strings.
_AUTH_FAILURE_PATTERNS = (
    "Authentication failure",
    "Unknown user name",
    "Unsupported security level",
    "Unknown security name",
    "Decryption error",
    "Wrong digest",
    "authorizationError",
    "Authentication failed for",
)
_TIMEOUT_PATTERNS = (
    "Timeout: No Response",
    "No Response from",
)
_UNREACHABLE_PATTERNS = (
    "Cannot find module",           # not unreachable, but fatal for this host
    "unknown host",
    "Unknown host",
    "No route to host",
    "Network is unreachable",
    "Connection refused",
)

# A walk that returns these for the very first OID means the agent has nothing
# in that subtree — normal, not an error.
_EMPTY_SUBTREE_PATTERNS = (
    "No Such Object available",
    "No Such Instance currently exists",
    "No more variables left in this MIB View",
    "End of MIB",
)


class SnmpError(Exception):
    """Any failure talking to a device."""


class SnmpAuthError(SnmpError):
    """The agent answered but rejected these credentials — try the next set."""


class SnmpTimeoutError(SnmpError):
    """The agent never answered. Trying other credentials would just wait again."""


class SnmpToolMissing(SnmpError):
    """net-snmp is not installed on this poller."""


@dataclass(frozen=True)
class Credential:
    """One SNMPv3 credential set.

    v3 only. v2c sends a community string in clear text on the wire, and the
    whole point of scanning production gear from a poller box is that the
    credentials survive being on the network.
    """

    name: str
    security_name: str
    auth_protocol: str = "SHA"       # MD5 | SHA | SHA-224 | SHA-256 | SHA-384 | SHA-512
    auth_passphrase: str = ""
    priv_protocol: str = "AES"       # DES | AES | AES-192 | AES-256
    priv_passphrase: str = ""
    security_level: str = ""         # derived when blank
    context: str = ""

    def level(self) -> str:
        """Work out the security level from which passphrases were supplied."""
        if self.security_level:
            return self.security_level
        if self.auth_passphrase and self.priv_passphrase:
            return "authPriv"
        if self.auth_passphrase:
            return "authNoPriv"
        return "noAuthNoPriv"

    def config_text(self) -> str:
        """Render this credential set as a net-snmp snmp.conf."""
        lines = [
            "# Generated by scripts/snmp-inventory. Contains SNMPv3 passphrases.",
            "defVersion 3",
            f"defSecurityLevel {self.level()}",
            f"defSecurityName {self.security_name}",
        ]
        if self.auth_passphrase:
            lines.append(f"defAuthType {self.auth_protocol}")
            lines.append(f"defAuthPassphrase {self.auth_passphrase}")
        if self.priv_passphrase:
            lines.append(f"defPrivType {self.priv_protocol}")
            lines.append(f"defPrivPassphrase {self.priv_passphrase}")
        if self.context:
            lines.append(f"defContext {self.context}")
        return "\n".join(lines) + "\n"


@dataclass
class VarBind:
    """One OID/value pair as net-snmp printed it."""

    oid: str          # numeric, no leading dot
    type: str         # STRING, INTEGER, Hex-STRING, OID, Timeticks, IpAddress...
    value: str        # already unquoted / de-hexed into a usable form

    def as_int(self, default: int | None = None) -> int | None:
        try:
            return int(self.value)
        except (TypeError, ValueError):
            return default


class CredentialSession:
    """A temp directory holding one credential set's snmp.conf.

    Used as a context manager so the passphrases on disk have a bounded life:

        with CredentialSession(cred) as session:
            binds = session.walk("10.0.0.1", "1.3.6.1.2.1.1")
    """

    def __init__(self, credential: Credential, timeout: int = 5, retries: int = 1,
                 use_bulk: bool = True, max_repetitions: int = 25):
        self.credential = credential
        self.timeout = timeout
        self.retries = retries
        self.use_bulk = use_bulk
        self.max_repetitions = max_repetitions
        self._dir: str | None = None

    def __enter__(self) -> CredentialSession:
        # 0700 by default from mkdtemp; the config inside is written 0600.
        self._dir = tempfile.mkdtemp(prefix="snmpinv-")
        path = os.path.join(self._dir, "snmp.conf")
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as handle:
            handle.write(self.credential.config_text())
        return self

    def __exit__(self, *exc_info) -> None:
        if self._dir:
            shutil.rmtree(self._dir, ignore_errors=True)
            self._dir = None

    def _env(self) -> dict[str, str]:
        env = dict(os.environ)
        # SNMPCONFPATH replaces the whole search path, so the operator's own
        # ~/.snmp/snmp.conf cannot leak a different community or user into a
        # scan and silently change which credentials were actually used.
        env["SNMPCONFPATH"] = self._dir or ""
        # net-snmp caches each agent's engine boots/time in its persistent
        # directory. Point that at the temp dir too: on a poller running as a
        # service account /var/lib/snmp is usually not writable, and a stale
        # engine time from a previous run causes spurious auth failures.
        env["SNMP_PERSISTENT_DIR"] = self._dir or ""
        return env

    def _run(self, tool: str, host: str, oid: str) -> str:
        if self._dir is None:
            raise RuntimeError("CredentialSession must be used as a context manager")
        binary = shutil.which(tool)
        if binary is None:
            raise SnmpToolMissing(
                f"{tool} not found — install net-snmp "
                "(apt install snmp / yum install net-snmp-utils)"
            )
        argv = [binary, "-On", "-Oe", "-Ot", "-t", str(self.timeout), "-r", str(self.retries)]
        if tool == "snmpbulkwalk":
            argv += ["-Cr", str(self.max_repetitions)]
        argv += [host, oid]
        # Note there is no -u/-A/-X/-l here on purpose: everything about the
        # credential comes from SNMPCONFPATH.
        try:
            proc = subprocess.run(
                argv,
                env=self._env(),
                capture_output=True,
                text=True,
                # A hung agent should not hang the scan. net-snmp's own -t/-r
                # bound each request, but this bounds the whole walk.
                timeout=max(30, self.timeout * (self.retries + 1) * 12),
            )
        except subprocess.TimeoutExpired as exc:
            raise SnmpTimeoutError(f"{tool} against {host} exceeded its overall time budget") from exc

        combined = f"{proc.stdout}\n{proc.stderr}"
        _raise_for_message(combined, host)
        return proc.stdout

    def walk(self, host: str, oid: str) -> list[VarBind]:
        """Walk a subtree. Returns [] when the agent has nothing there."""
        if self.use_bulk:
            try:
                return parse_varbinds(self._run("snmpbulkwalk", host, oid))
            except SnmpAuthError:
                raise
            except SnmpTimeoutError:
                raise
            except SnmpError:
                # Some older agents answer GETNEXT fine but mishandle GETBULK.
                # Falling back costs one extra round trip and rescues the walk.
                pass
        return parse_varbinds(self._run("snmpwalk", host, oid))

    def get(self, host: str, oids: list[str]) -> dict[str, VarBind]:
        """Fetch scalars. Missing instances are simply absent from the result."""
        if not oids:
            return {}
        binary = shutil.which("snmpget")
        if binary is None:
            raise SnmpToolMissing("snmpget not found — install net-snmp")
        argv = [binary, "-On", "-Oe", "-Ot", "-t", str(self.timeout), "-r", str(self.retries), host]
        argv += oids
        try:
            proc = subprocess.run(argv, env=self._env(), capture_output=True, text=True,
                                  timeout=max(30, self.timeout * (self.retries + 1) * 4))
        except subprocess.TimeoutExpired as exc:
            raise SnmpTimeoutError(f"snmpget against {host} timed out") from exc
        combined = f"{proc.stdout}\n{proc.stderr}"
        # snmpget returns non-zero when *any* requested OID is absent, which is
        # routine when probing several vendors' scalars, so only genuine
        # transport/auth failures are escalated.
        _raise_for_message(combined, host)
        return {bind.oid: bind for bind in parse_varbinds(proc.stdout)}

    def probe(self, host: str) -> bool:
        """Cheapest possible check that these credentials work on this host."""
        binds = self.get(host, ["1.3.6.1.2.1.1.2.0"])
        return bool(binds)


def _raise_for_message(text: str, host: str) -> None:
    """Turn net-snmp's diagnostics into the right exception type.

    The distinction that matters is auth-failure versus timeout. On an auth
    failure the next credential set is worth trying; on a timeout the host is
    not answering at all and trying five more credential sets just multiplies
    the wait by five.
    """
    for pattern in _AUTH_FAILURE_PATTERNS:
        if pattern in text:
            raise SnmpAuthError(f"{host}: {pattern}")
    for pattern in _TIMEOUT_PATTERNS:
        if pattern in text:
            raise SnmpTimeoutError(f"{host}: no response")
    for pattern in _UNREACHABLE_PATTERNS:
        if pattern in text:
            raise SnmpTimeoutError(f"{host}: {pattern}")


# `.1.3.6.1.2.1.1.1.0 = STRING: "Linux host"` — the value may then continue on
# following lines, because plenty of devices put newlines in sysDescr.
_LINE = re.compile(r"^(\.?[\d.]+)\s+=\s+(?:([A-Za-z0-9-]+):\s?)?(.*)$")
_HEX_BYTE = re.compile(r"^[0-9A-Fa-f]{2}$")


def parse_varbinds(text: str) -> list[VarBind]:
    """Parse net-snmp `-On -Oe` output into VarBinds.

    Handles values that span several lines. Cisco's sysDescr is the usual
    culprit — it is a small paragraph with embedded newlines, and a parser that
    assumes one varbind per line silently truncates it and then fails to find a
    version in it.
    """
    binds: list[VarBind] = []
    pending_oid = pending_type = None
    pending_value: list[str] = []

    def flush() -> None:
        if pending_oid is None:
            return
        raw = "\n".join(pending_value)
        binds.append(VarBind(pending_oid, pending_type or "", _clean_value(pending_type or "", raw)))

    for line in text.splitlines():
        if not line.strip():
            continue
        match = _LINE.match(line)
        if match and not _is_empty_subtree_marker(line):
            flush()
            pending_oid = match.group(1).lstrip(".")
            pending_type = match.group(2)
            pending_value = [match.group(3)]
        elif _is_empty_subtree_marker(line):
            # "No Such Object available on this agent at this OID" and friends:
            # the subtree is simply not implemented. Drop the varbind entirely
            # so callers see an absent key rather than a bogus value.
            flush()
            pending_oid = pending_type = None
            pending_value = []
        elif pending_oid is not None:
            pending_value.append(line)
    flush()
    return binds


def _is_empty_subtree_marker(line: str) -> bool:
    return any(pattern in line for pattern in _EMPTY_SUBTREE_PATTERNS)


def _clean_value(value_type: str, raw: str) -> str:
    """Normalise a printed value into something usable.

    Hex-STRINGs become colon-separated uppercase (MAC-shaped), quoted strings
    lose their quotes, Timeticks lose the human-readable tail, and OIDs lose
    their leading dot so they compare equal to the OIDs we build ourselves.
    """
    raw = raw.strip()
    if value_type == "Hex-STRING":
        parts = [p for p in raw.replace("\n", " ").split(" ") if _HEX_BYTE.match(p)]
        return ":".join(p.upper() for p in parts)
    if value_type == "Timeticks":
        # `(123456) 0:20:34.56` -> `123456`
        match = re.match(r"\((\d+)\)", raw)
        if match:
            return match.group(1)
    if value_type == "OID":
        return raw.lstrip(".")
    if len(raw) >= 2 and raw[0] == '"' and raw[-1] == '"':
        return raw[1:-1]
    return raw


def column_index(oid: str, column_oid: str) -> str | None:
    """Return the table index part of `oid` if it sits under `column_oid`.

    Table rows are identified by whatever follows the column OID, which for
    most tables is a single integer but for ipAddressTable and the Aruba AP
    table is a multi-part index that we decode separately.
    """
    prefix = column_oid.rstrip(".") + "."
    if not oid.startswith(prefix):
        return None
    return oid[len(prefix):]


def collect_column(binds: list[VarBind], column_oid: str) -> dict[str, VarBind]:
    """Pick one column out of a walked table, keyed by row index."""
    out: dict[str, VarBind] = {}
    for bind in binds:
        index = column_index(bind.oid, column_oid)
        if index is not None:
            out[index] = bind
    return out
