#!/usr/bin/env bash
# Generate local dev env files from the committed .example templates, filling in
# fresh random secrets. Idempotent: existing files/blocks are left untouched.
set -euo pipefail
cd "$(dirname "$0")/.."

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"; }

if [ ! -f .env ]; then
  cp .env.example .env
  printf 'SUPERUSER_PASSWORD=%s\n' "$(gen 20)" >>.env
  echo "created .env (dev superuser password inside)"
fi

if [ ! -f env/netbox.env ]; then
  DB_PASSWORD=$(gen 24)
  REDIS_PASSWORD=$(gen 24)
  REDIS_CACHE_PASSWORD=$(gen 24)
  sed -e "s/{{SECRET_KEY}}/$(gen 60)/" \
    -e "s/{{API_TOKEN_PEPPER}}/$(gen 50)/" \
    -e "s/{{DB_PASSWORD}}/$DB_PASSWORD/" \
    -e "s/{{REDIS_PASSWORD}}/$REDIS_PASSWORD/" \
    -e "s/{{REDIS_CACHE_PASSWORD}}/$REDIS_CACHE_PASSWORD/" \
    env/netbox.env.example >env/netbox.env
  sed "s/{{DB_PASSWORD}}/$DB_PASSWORD/" env/postgres.env.example >env/postgres.env
  sed "s/{{REDIS_PASSWORD}}/$REDIS_PASSWORD/" env/redis.env.example >env/redis.env
  sed "s/{{REDIS_CACHE_PASSWORD}}/$REDIS_CACHE_PASSWORD/" env/redis-cache.env.example >env/redis-cache.env
  echo "created env/*.env with fresh secrets"
fi

# --- Discovery stack (Diode + orb-agent) secrets --------------------------
if ! grep -q '^DIODE_TAG=' .env; then
  cat >>.env <<EOF

# --- discovery (Diode + orb-agent) — generated by scripts/init-dev-env.sh ---
DIODE_TAG=2.1.0
DIODE_NGINX_PORT=8090
REDIS_PASSWORD=$(gen 32)
REDIS_HOST=diode-redis
REDIS_PORT=6378
REDIS_USERNAME=
LOGGING_LEVEL=DEBUG
SENTRY_DSN=
MIGRATION_ENABLED=true
POSTGRES_HOST=diode-postgres
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(gen 32)
DIODE_POSTGRES_DB_NAME=diode
DIODE_POSTGRES_USER=diode
DIODE_POSTGRES_PASSWORD=$(gen 32)
TELEMETRY_ENVIRONMENT=dev
TELEMETRY_METRICS_EXPORTER=prometheus
TELEMETRY_TRACES_EXPORTER=none
HYDRA_POSTGRES_DB_NAME=hydra
HYDRA_POSTGRES_USER=hydra
HYDRA_POSTGRES_PASSWORD=$(gen 32)
HYDRA_STRATEGIES_ACCESS_TOKEN=jwt
HYDRA_STRATEGIES_REFRESH_TOKEN=jwt
HYDRA_STRATEGIES_JWT_SCOPE_CLAIM=both
HYDRA_TTL_ACCESS_TOKEN=1h
HYDRA_OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public
HYDRA_URLS_SELF_ISSUER=http://127.0.0.1:4444
HYDRA_SECRETS_SYSTEM_0=$(gen 48)
AUTH_HTTP_PORT=8080
OAUTH2_PUBLIC_SERVER_URL=http://hydra:4444
OAUTH2_ADMIN_SERVER_URL=http://hydra:4445
DIODE_AUTH_TOKEN_URL=http://diode-auth:8080/token
DIODE_TO_NETBOX_CLIENT_ID=diode-to-netbox
DIODE_TO_NETBOX_CLIENT_SECRET=$(gen 48)
NETBOX_DIODE_PLUGIN_API_BASE_URL=http://netbox:8080/api/plugins/diode
NETBOX_DIODE_PLUGIN_SKIP_TLS_VERIFY=false
AUTO_APPLY_CHANGESETS=true
ENABLE_GRAPH_DB=false
INGESTION_LOG_PROCESSOR_BATCH_SIZE=50
INGESTION_LOG_PROCESSOR_CONCURRENCY=1
AUTO_APPLY_PROCESSOR_BATCH_SIZE=50
AUTO_APPLY_PROCESSOR_CONCURRENCY=1
NETBOX_TO_DIODE_CLIENT_SECRET=$(gen 48)
DIODE_INGEST_CLIENT_ID=diode-ingest
DIODE_INGEST_CLIENT_SECRET=$(gen 48)
DIODE_GRPC_TARGET=grpc://diode-nginx:80/diode
# Device credentials used by discovery/agent.yaml — fill in (never committed):
DISCOVERY_SNMP_USER=
DISCOVERY_SNMP_AUTH_PASS=
DISCOVERY_SNMP_PRIV_PASS=
DISCOVERY_SSH_USER=
DISCOVERY_SSH_PASS=
EOF
  echo "appended discovery secrets block to .env (fill DISCOVERY_* device creds)"
fi

if [ ! -f discovery/oauth2/client/client-credentials.json ]; then
  envval() { grep "^$1=" .env | tail -1 | cut -d= -f2-; }
  sed -e "s/{{DIODE_INGEST_CLIENT_SECRET}}/$(envval DIODE_INGEST_CLIENT_SECRET)/" \
    -e "s/{{DIODE_TO_NETBOX_CLIENT_SECRET}}/$(envval DIODE_TO_NETBOX_CLIENT_SECRET)/" \
    -e "s/{{NETBOX_TO_DIODE_CLIENT_SECRET}}/$(envval NETBOX_TO_DIODE_CLIENT_SECRET)/" \
    discovery/oauth2/client/client-credentials.json.example \
    >discovery/oauth2/client/client-credentials.json
  echo "created discovery/oauth2/client/client-credentials.json"
fi

echo "dev env ready — next: docker compose build && docker compose up -d"
