#!/usr/bin/env bash
# Generate the local dev env files from the committed .example templates,
# filling in fresh random secrets.
#
# Safe to re-run: every file is created only if missing, and the companion
# files are derived from env/netbox.env so their shared passwords always match
# even when only some of them exist.
set -euo pipefail
cd "$(dirname "$0")/.."

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"; }

# Read a KEY=value out of an env file.
getval() { grep "^$2=" "$1" | tail -1 | cut -d= -f2-; }

created=()

# --- .env: selects the compose overlay chain, so nothing works without it ----
if [ ! -f .env ]; then
  cp .env.example .env
  printf 'SUPERUSER_PASSWORD=%s\n' "$(gen 20)" >>.env
  created+=(".env")
else
  # Existing .env: add any settings introduced since it was generated. Without
  # this, a new variable silently falls back to its compose default — which is
  # how BIND_ADDRESS ended up pinned to loopback on existing checkouts.
  added=()
  while IFS= read -r line; do
    case "$line" in
      ''|'#'*) continue ;;
      *=*) key=${line%%=*} ;;
      *) continue ;;
    esac
    if ! grep -q "^${key}=" .env; then
      printf '%s\n' "$line" >>.env
      added+=("$key")
    fi
  done <.env.example
  if [ ${#added[@]} -gt 0 ]; then
    created+=(".env: added ${added[*]}")
  fi
fi

# --- env/netbox.env is the source of truth for the shared passwords ---------
if [ ! -f env/netbox.env ]; then
  sed -e "s/{{SECRET_KEY}}/$(gen 60)/" \
    -e "s/{{API_TOKEN_PEPPER}}/$(gen 50)/" \
    -e "s/{{DB_PASSWORD}}/$(gen 24)/" \
    -e "s/{{REDIS_PASSWORD}}/$(gen 24)/" \
    -e "s/{{REDIS_CACHE_PASSWORD}}/$(gen 24)/" \
    env/netbox.env.example >env/netbox.env
  created+=("env/netbox.env")
fi

# --- companions, derived so they cannot drift out of sync -------------------
db_password=$(getval env/netbox.env DB_PASSWORD)
redis_password=$(getval env/netbox.env REDIS_PASSWORD)
redis_cache_password=$(getval env/netbox.env REDIS_CACHE_PASSWORD)

if [ ! -f env/postgres.env ]; then
  sed "s/{{DB_PASSWORD}}/$db_password/" env/postgres.env.example >env/postgres.env
  created+=("env/postgres.env")
fi
if [ ! -f env/redis.env ]; then
  sed "s/{{REDIS_PASSWORD}}/$redis_password/" env/redis.env.example >env/redis.env
  created+=("env/redis.env")
fi
if [ ! -f env/redis-cache.env ]; then
  sed "s/{{REDIS_CACHE_PASSWORD}}/$redis_cache_password/" \
    env/redis-cache.env.example >env/redis-cache.env
  created+=("env/redis-cache.env")
fi

# --- discovery stack (Diode + orb-agent) secrets ---------------------------
if ! grep -q '^DIODE_TAG=' .env; then
  cat >>.env <<EOF

# --- discovery (Diode + orb-agent) — generated by scripts/init-dev-env.sh ---
DIODE_TAG=2.1.0
DIODE_NGINX_PORT=8090
REDIS_PASSWORD=$(gen 32)
REDIS_HOST=diode-redis
REDIS_PORT=6378
REDIS_USERNAME=
LOGGING_LEVEL=DEBUG
SENTRY_DSN=
MIGRATION_ENABLED=true
POSTGRES_HOST=diode-postgres
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(gen 32)
DIODE_POSTGRES_DB_NAME=diode
DIODE_POSTGRES_USER=diode
DIODE_POSTGRES_PASSWORD=$(gen 32)
TELEMETRY_ENVIRONMENT=dev
TELEMETRY_METRICS_EXPORTER=prometheus
TELEMETRY_TRACES_EXPORTER=none
HYDRA_POSTGRES_DB_NAME=hydra
HYDRA_POSTGRES_USER=hydra
HYDRA_POSTGRES_PASSWORD=$(gen 32)
HYDRA_STRATEGIES_ACCESS_TOKEN=jwt
HYDRA_STRATEGIES_REFRESH_TOKEN=jwt
HYDRA_STRATEGIES_JWT_SCOPE_CLAIM=both
HYDRA_TTL_ACCESS_TOKEN=1h
HYDRA_OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public
HYDRA_URLS_SELF_ISSUER=http://127.0.0.1:4444
HYDRA_SECRETS_SYSTEM_0=$(gen 48)
AUTH_HTTP_PORT=8080
OAUTH2_PUBLIC_SERVER_URL=http://hydra:4444
OAUTH2_ADMIN_SERVER_URL=http://hydra:4445
DIODE_AUTH_TOKEN_URL=http://diode-auth:8080/token
DIODE_TO_NETBOX_CLIENT_ID=diode-to-netbox
DIODE_TO_NETBOX_CLIENT_SECRET=$(gen 48)
NETBOX_DIODE_PLUGIN_API_BASE_URL=http://netbox:8080/api/plugins/diode
NETBOX_DIODE_PLUGIN_SKIP_TLS_VERIFY=false
AUTO_APPLY_CHANGESETS=true
ENABLE_GRAPH_DB=false
INGESTION_LOG_PROCESSOR_BATCH_SIZE=50
INGESTION_LOG_PROCESSOR_CONCURRENCY=1
AUTO_APPLY_PROCESSOR_BATCH_SIZE=50
AUTO_APPLY_PROCESSOR_CONCURRENCY=1
NETBOX_TO_DIODE_CLIENT_SECRET=$(gen 48)
DIODE_INGEST_CLIENT_ID=diode-ingest
DIODE_INGEST_CLIENT_SECRET=$(gen 48)
DIODE_GRPC_TARGET=grpc://diode-nginx:80/diode
# Device credentials used by discovery/agent.yaml — fill in (never committed):
DISCOVERY_SNMP_USER=
DISCOVERY_SNMP_AUTH_PASS=
DISCOVERY_SNMP_PRIV_PASS=
DISCOVERY_SSH_USER=
DISCOVERY_SSH_PASS=
# Cisco Support API credentials for netbox_refresh EoX sync (optional):
CISCO_CLIENT_ID=
CISCO_CLIENT_SECRET=
EOF
  created+=(".env discovery block")
fi

if [ ! -f discovery/oauth2/client/client-credentials.json ]; then
  mkdir -p discovery/oauth2/client
  sed -e "s/{{DIODE_INGEST_CLIENT_SECRET}}/$(getval .env DIODE_INGEST_CLIENT_SECRET)/" \
    -e "s/{{DIODE_TO_NETBOX_CLIENT_SECRET}}/$(getval .env DIODE_TO_NETBOX_CLIENT_SECRET)/" \
    -e "s/{{NETBOX_TO_DIODE_CLIENT_SECRET}}/$(getval .env NETBOX_TO_DIODE_CLIENT_SECRET)/" \
    discovery/oauth2/client/client-credentials.json.example \
    >discovery/oauth2/client/client-credentials.json
  created+=("discovery/oauth2/client/client-credentials.json")
fi

# --- verify: every file compose needs must now exist ------------------------
missing=()
for f in .env env/netbox.env env/postgres.env env/redis.env env/redis-cache.env; do
  [ -f "$f" ] || missing+=("$f")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "ERROR: still missing after setup: ${missing[*]}" >&2
  exit 1
fi

if [ ${#created[@]} -gt 0 ]; then
  printf 'created: %s\n' "${created[*]}"
else
  echo 'nothing to do — dev env files already present'
fi
echo 'dev env ready — next: docker compose build && docker compose up -d'
