# Generated by Django 6.0.7 on 2026-08-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotevendor',
            name='is_third_party_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
